USE [SCRA]
GO

/****** Object:  Table [dbo].[RulePBP]    Script Date: 2/18/2019 8:50:01 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('[dbo].[RulePBP]' , 'U') IS NOT NULL  
DROP TABLE [dbo].[RulePBP]
GO

CREATE TABLE [dbo].[RulePBP](
	[RuleId] [int] NOT NULL,
	[ContractPBPId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RuleId] ASC,
	[ContractPBPId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_RulePBP] UNIQUE NONCLUSTERED 
(
	[RuleId] ASC,
	[ContractPBPId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[RulePBP]  WITH CHECK ADD  CONSTRAINT [FK_RulePBP_ContractPBP] FOREIGN KEY(ContractPBPId)
REFERENCES [dbo].[ContractPBP] ([ContractPBPId])
GO

ALTER TABLE [dbo].[RulePBP] CHECK CONSTRAINT [FK_RulePBP_ContractPBP]
GO

ALTER TABLE [dbo].[RulePBP]  WITH CHECK ADD  CONSTRAINT [FK_RulePBP_Rule] FOREIGN KEY([RuleId])
REFERENCES [dbo].[Rule] ([RuleId])
GO

ALTER TABLE [dbo].[RulePBP] CHECK CONSTRAINT [FK_RulePBP_Rule]
GO




