USE [SCRA]
GO
/****** Object:  Table [dbo].[Application]    Script Date: 1/28/2019 9:28:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Application](
	[ApplicationId] [int] NOT NULL,
	[Description] [varchar](50) NOT NULL,
	[Code] [varchar](20) NOT NULL,
 CONSTRAINT [PK_Application] PRIMARY KEY CLUSTERED 
(
	[ApplicationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Contract]    Script Date: 1/28/2019 9:28:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contract](
	[ContractId] [int] NOT NULL,
	[Description] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Contract] PRIMARY KEY CLUSTERED 
(
	[ContractId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ContractPBP]    Script Date: 1/28/2019 9:28:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ContractPBP](
	[ContractPBPId] [int] IDENTITY(1,1) NOT NULL,
	[ContractId] [int] NOT NULL,
	[PBPId] [int] NOT NULL,
 CONSTRAINT [PK_ContractPBP] PRIMARY KEY CLUSTERED 
(
	[ContractPBPId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Measure]    Script Date: 1/28/2019 9:28:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Measure](
	[MeasureId] [int] NOT NULL,
	[Description] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Measure] PRIMARY KEY CLUSTERED 
(
	[MeasureId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PBP]    Script Date: 1/28/2019 9:28:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PBP](
	[PBPId] [int] NOT NULL,
	[Description] [varchar](50) NOT NULL,
 CONSTRAINT [PK_PBP] PRIMARY KEY CLUSTERED 
(
	[PBPId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Rule]    Script Date: 1/28/2019 9:28:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rule](
	[RuleId] [int] IDENTITY(1,1) NOT NULL,
	[Code] [varchar](50) NOT NULL,
	[Description] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Rule] PRIMARY KEY CLUSTERED 
(
	[RuleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[RuleApplication]    Script Date: 1/28/2019 9:28:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RuleApplication](
	[RuleId] [int] NOT NULL,
	[ApplicationId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RuleId] ASC,
	[ApplicationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[RuleContract]    Script Date: 1/28/2019 9:28:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RuleContract](
	[RuleId] [int] NOT NULL,
	[ContractId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RuleId] ASC,
	[ContractId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[RuleMeasure]    Script Date: 1/28/2019 9:28:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RuleMeasure](
	[RuleId] [int] NOT NULL,
	[MeasureId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RuleId] ASC,
	[MeasureId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[RulePBP]    Script Date: 1/28/2019 9:28:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RulePBP](
	[RuleId] [int] NOT NULL,
	[PBPId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RuleId] ASC,
	[PBPId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[RuleSegment]    Script Date: 1/28/2019 9:28:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RuleSegment](
	[RuleId] [int] NOT NULL,
	[SegmentId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RuleId] ASC,
	[SegmentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[RuleTIN]    Script Date: 1/28/2019 9:28:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RuleTIN](
	[RuleId] [int] NOT NULL,
	[TINId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RuleId] ASC,
	[TINId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Segment]    Script Date: 1/28/2019 9:28:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Segment](
	[SegmentId] [int] NOT NULL,
	[Description] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Segment] PRIMARY KEY CLUSTERED 
(
	[SegmentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TIN]    Script Date: 1/28/2019 9:28:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIN](
	[TINId] [int] NOT NULL,
	[Description] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TIN] PRIMARY KEY CLUSTERED 
(
	[TINId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[User]    Script Date: 1/28/2019 9:28:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[UserId] [int] NOT NULL,
	[UserName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[UserApplication]    Script Date: 1/28/2019 9:28:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserApplication](
	[UserId] [int] NOT NULL,
	[ApplicationId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[ApplicationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[UserRule]    Script Date: 1/28/2019 9:28:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserRule](
	[UserId] [int] NOT NULL,
	[RuleId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RuleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Index [IX_ContractPBP]    Script Date: 1/28/2019 9:28:05 AM ******/
ALTER TABLE [dbo].[ContractPBP] ADD  CONSTRAINT [IX_ContractPBP] UNIQUE NONCLUSTERED 
(
	[ContractId] ASC,
	[PBPId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_RuleApplication]    Script Date: 1/28/2019 9:28:05 AM ******/
ALTER TABLE [dbo].[RuleApplication] ADD  CONSTRAINT [IX_RuleApplication] UNIQUE NONCLUSTERED 
(
	[RuleId] ASC,
	[ApplicationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_RuleContract]    Script Date: 1/28/2019 9:28:05 AM ******/
ALTER TABLE [dbo].[RuleContract] ADD  CONSTRAINT [IX_RuleContract] UNIQUE NONCLUSTERED 
(
	[RuleId] ASC,
	[ContractId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_RuleMeasure]    Script Date: 1/28/2019 9:28:05 AM ******/
ALTER TABLE [dbo].[RuleMeasure] ADD  CONSTRAINT [IX_RuleMeasure] UNIQUE NONCLUSTERED 
(
	[RuleId] ASC,
	[MeasureId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_RulePBP]    Script Date: 1/28/2019 9:28:05 AM ******/
ALTER TABLE [dbo].[RulePBP] ADD  CONSTRAINT [IX_RulePBP] UNIQUE NONCLUSTERED 
(
	[RuleId] ASC,
	[PBPId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_RuleSegment]    Script Date: 1/28/2019 9:28:05 AM ******/
ALTER TABLE [dbo].[RuleSegment] ADD  CONSTRAINT [IX_RuleSegment] UNIQUE NONCLUSTERED 
(
	[RuleId] ASC,
	[SegmentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_RuleTIN]    Script Date: 1/28/2019 9:28:05 AM ******/
ALTER TABLE [dbo].[RuleTIN] ADD  CONSTRAINT [IX_RuleTIN] UNIQUE NONCLUSTERED 
(
	[RuleId] ASC,
	[TINId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_UserApplication]    Script Date: 1/28/2019 9:28:05 AM ******/
ALTER TABLE [dbo].[UserApplication] ADD  CONSTRAINT [IX_UserApplication] UNIQUE NONCLUSTERED 
(
	[UserId] ASC,
	[ApplicationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_UserRule]    Script Date: 1/28/2019 9:28:05 AM ******/
ALTER TABLE [dbo].[UserRule] ADD  CONSTRAINT [IX_UserRule] UNIQUE NONCLUSTERED 
(
	[RuleId] ASC,
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ContractPBP]  WITH CHECK ADD  CONSTRAINT [FK_ContractPBP_Contract] FOREIGN KEY([ContractId])
REFERENCES [dbo].[Contract] ([ContractId])
GO
ALTER TABLE [dbo].[ContractPBP] CHECK CONSTRAINT [FK_ContractPBP_Contract]
GO
ALTER TABLE [dbo].[ContractPBP]  WITH CHECK ADD  CONSTRAINT [FK_ContractPBP_PBP] FOREIGN KEY([PBPId])
REFERENCES [dbo].[PBP] ([PBPId])
GO
ALTER TABLE [dbo].[ContractPBP] CHECK CONSTRAINT [FK_ContractPBP_PBP]
GO
ALTER TABLE [dbo].[RuleApplication]  WITH CHECK ADD  CONSTRAINT [FK_RuleApplication_Application] FOREIGN KEY([ApplicationId])
REFERENCES [dbo].[Application] ([ApplicationId])
GO
ALTER TABLE [dbo].[RuleApplication] CHECK CONSTRAINT [FK_RuleApplication_Application]
GO
ALTER TABLE [dbo].[RuleApplication]  WITH CHECK ADD  CONSTRAINT [FK_RuleApplication_Rule] FOREIGN KEY([RuleId])
REFERENCES [dbo].[Rule] ([RuleId])
GO
ALTER TABLE [dbo].[RuleApplication] CHECK CONSTRAINT [FK_RuleApplication_Rule]
GO
ALTER TABLE [dbo].[RuleContract]  WITH CHECK ADD  CONSTRAINT [FK_RuleContract_Contract] FOREIGN KEY([ContractId])
REFERENCES [dbo].[Contract] ([ContractId])
GO
ALTER TABLE [dbo].[RuleContract] CHECK CONSTRAINT [FK_RuleContract_Contract]
GO
ALTER TABLE [dbo].[RuleContract]  WITH CHECK ADD  CONSTRAINT [FK_RuleContract_Rule] FOREIGN KEY([RuleId])
REFERENCES [dbo].[Rule] ([RuleId])
GO
ALTER TABLE [dbo].[RuleContract] CHECK CONSTRAINT [FK_RuleContract_Rule]
GO
ALTER TABLE [dbo].[RuleMeasure]  WITH CHECK ADD  CONSTRAINT [FK_RuleMeasure_Measure] FOREIGN KEY([MeasureId])
REFERENCES [dbo].[Measure] ([MeasureId])
GO
ALTER TABLE [dbo].[RuleMeasure] CHECK CONSTRAINT [FK_RuleMeasure_Measure]
GO
ALTER TABLE [dbo].[RuleMeasure]  WITH CHECK ADD  CONSTRAINT [FK_RuleMeasure_Rule] FOREIGN KEY([RuleId])
REFERENCES [dbo].[Rule] ([RuleId])
GO
ALTER TABLE [dbo].[RuleMeasure] CHECK CONSTRAINT [FK_RuleMeasure_Rule]
GO
ALTER TABLE [dbo].[RulePBP]  WITH CHECK ADD  CONSTRAINT [FK_RulePBP_PBP] FOREIGN KEY([PBPId])
REFERENCES [dbo].[PBP] ([PBPId])
GO
ALTER TABLE [dbo].[RulePBP] CHECK CONSTRAINT [FK_RulePBP_PBP]
GO
ALTER TABLE [dbo].[RulePBP]  WITH CHECK ADD  CONSTRAINT [FK_RulePBP_Rule] FOREIGN KEY([RuleId])
REFERENCES [dbo].[Rule] ([RuleId])
GO
ALTER TABLE [dbo].[RulePBP] CHECK CONSTRAINT [FK_RulePBP_Rule]
GO
ALTER TABLE [dbo].[RuleSegment]  WITH CHECK ADD  CONSTRAINT [FK_RuleSegment_Rule] FOREIGN KEY([RuleId])
REFERENCES [dbo].[Rule] ([RuleId])
GO
ALTER TABLE [dbo].[RuleSegment] CHECK CONSTRAINT [FK_RuleSegment_Rule]
GO
ALTER TABLE [dbo].[RuleSegment]  WITH CHECK ADD  CONSTRAINT [FK_RuleSegment_Segment] FOREIGN KEY([SegmentId])
REFERENCES [dbo].[Segment] ([SegmentId])
GO
ALTER TABLE [dbo].[RuleSegment] CHECK CONSTRAINT [FK_RuleSegment_Segment]
GO
ALTER TABLE [dbo].[RuleTIN]  WITH CHECK ADD  CONSTRAINT [FK_RuleTIN_Rule] FOREIGN KEY([RuleId])
REFERENCES [dbo].[Rule] ([RuleId])
GO
ALTER TABLE [dbo].[RuleTIN] CHECK CONSTRAINT [FK_RuleTIN_Rule]
GO
ALTER TABLE [dbo].[RuleTIN]  WITH CHECK ADD  CONSTRAINT [FK_RuleTIN_TIN] FOREIGN KEY([TINId])
REFERENCES [dbo].[TIN] ([TINId])
GO
ALTER TABLE [dbo].[RuleTIN] CHECK CONSTRAINT [FK_RuleTIN_TIN]
GO
ALTER TABLE [dbo].[UserApplication]  WITH CHECK ADD  CONSTRAINT [FK_UserApplication_Application] FOREIGN KEY([ApplicationId])
REFERENCES [dbo].[Application] ([ApplicationId])
GO
ALTER TABLE [dbo].[UserApplication] CHECK CONSTRAINT [FK_UserApplication_Application]
GO
ALTER TABLE [dbo].[UserApplication]  WITH CHECK ADD  CONSTRAINT [FK_UserApplication_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([UserId])
GO
ALTER TABLE [dbo].[UserApplication] CHECK CONSTRAINT [FK_UserApplication_User]
GO
ALTER TABLE [dbo].[UserRule]  WITH CHECK ADD  CONSTRAINT [FK_UserRule_Rule] FOREIGN KEY([RuleId])
REFERENCES [dbo].[Rule] ([RuleId])
GO
ALTER TABLE [dbo].[UserRule] CHECK CONSTRAINT [FK_UserRule_Rule]
GO
ALTER TABLE [dbo].[UserRule]  WITH CHECK ADD  CONSTRAINT [FK_UserRule_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([UserId])
GO
ALTER TABLE [dbo].[UserRule] CHECK CONSTRAINT [FK_UserRule_User]
GO
